--
-- PostgreSQL database dump
--

\restrict R04ZdVkMHEGeedWPU8zp0oZqw6FbgZyab3MW8J7s8IK6HSTu7LrS7DwZdMHdA4R

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg12+2)
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: military_admin
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO military_admin;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assignments; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.assignments (
    id bigint NOT NULL,
    assigned_at timestamp(6) without time zone NOT NULL,
    personnel_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    base_id bigint NOT NULL,
    equipment_type_id bigint
);


ALTER TABLE public.assignments OWNER TO military_admin;

--
-- Name: assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bases; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.bases (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.bases OWNER TO military_admin;

--
-- Name: bases_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.bases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_type; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.equipment_type (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.equipment_type OWNER TO military_admin;

--
-- Name: equipment_type_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.equipment_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenditures; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.expenditures (
    id bigint NOT NULL,
    expended_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    base_id bigint NOT NULL,
    equipment_type_id bigint NOT NULL
);


ALTER TABLE public.expenditures OWNER TO military_admin;

--
-- Name: expenditures_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.expenditures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenditures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchases; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.purchases (
    id bigint NOT NULL,
    purchase_date timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    base_id bigint NOT NULL,
    equipment_type_id bigint NOT NULL
);


ALTER TABLE public.purchases OWNER TO military_admin;

--
-- Name: purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.purchases ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transfers; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.transfers (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    transfer_date timestamp(6) without time zone NOT NULL,
    equipment_type_id bigint NOT NULL,
    from_base_id bigint NOT NULL,
    to_base_id bigint NOT NULL
);


ALTER TABLE public.transfers OWNER TO military_admin;

--
-- Name: transfers_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.transfers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transfers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: military_admin
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    base_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'BASE_COMMANDER'::character varying, 'LOGISTICS_OFFICER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO military_admin;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: military_admin
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: assignments; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.assignments (id, assigned_at, personnel_name, quantity, base_id, equipment_type_id) FROM stdin;
1	2026-10-22 15:02:00	Bhola Ram	10	1	1
\.


--
-- Data for Name: bases; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.bases (id, name) FROM stdin;
1	Base Beta
2	Base Alpha
7	Test Base
\.


--
-- Data for Name: equipment_type; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.equipment_type (id, category, name) FROM stdin;
1	Weapon	Rifle
\.


--
-- Data for Name: expenditures; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.expenditures (id, expended_at, quantity, base_id, equipment_type_id) FROM stdin;
1	2026-10-31 16:05:00	10	1	1
\.


--
-- Data for Name: purchases; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.purchases (id, purchase_date, quantity, base_id, equipment_type_id) FROM stdin;
\.


--
-- Data for Name: transfers; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.transfers (id, quantity, transfer_date, equipment_type_id, from_base_id, to_base_id) FROM stdin;
1	10	2026-10-02 13:49:00	1	1	2
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: military_admin
--

COPY public.users (id, password, role, username, base_id) FROM stdin;
1	$2a$10$5j0Pt61GFqG.yHiox80QHOMzeVkUamsZrAUbl8u.KxmiygrE2lNMW	ADMIN	admin	\N
\.


--
-- Name: assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.assignments_id_seq', 1, true);


--
-- Name: bases_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.bases_id_seq', 7, true);


--
-- Name: equipment_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.equipment_type_id_seq', 1, true);


--
-- Name: expenditures_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.expenditures_id_seq', 1, true);


--
-- Name: purchases_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.purchases_id_seq', 1, false);


--
-- Name: transfers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.transfers_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: military_admin
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: assignments assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);


--
-- Name: bases bases_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.bases
    ADD CONSTRAINT bases_pkey PRIMARY KEY (id);


--
-- Name: equipment_type equipment_type_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.equipment_type
    ADD CONSTRAINT equipment_type_pkey PRIMARY KEY (id);


--
-- Name: expenditures expenditures_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.expenditures
    ADD CONSTRAINT expenditures_pkey PRIMARY KEY (id);


--
-- Name: purchases purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT purchases_pkey PRIMARY KEY (id);


--
-- Name: transfers transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT transfers_pkey PRIMARY KEY (id);


--
-- Name: bases ukji1wujytmfp28mst0mrqo6aa2; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.bases
    ADD CONSTRAINT ukji1wujytmfp28mst0mrqo6aa2 UNIQUE (name);


--
-- Name: equipment_type ukly5pm93u4ps4l4936g1neschk; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.equipment_type
    ADD CONSTRAINT ukly5pm93u4ps4l4936g1neschk UNIQUE (name);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: purchases fk20ifnifc8kisbjap9jurnkf9a; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT fk20ifnifc8kisbjap9jurnkf9a FOREIGN KEY (equipment_type_id) REFERENCES public.equipment_type(id);


--
-- Name: users fk42vye4llcsjlhu40luxer3s2q; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk42vye4llcsjlhu40luxer3s2q FOREIGN KEY (base_id) REFERENCES public.bases(id);


--
-- Name: transfers fkbygujo0me1kwidph3r3wi6ppe; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkbygujo0me1kwidph3r3wi6ppe FOREIGN KEY (to_base_id) REFERENCES public.bases(id);


--
-- Name: expenditures fkegudip6r0gtcpyhd9nu5bojgr; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.expenditures
    ADD CONSTRAINT fkegudip6r0gtcpyhd9nu5bojgr FOREIGN KEY (base_id) REFERENCES public.bases(id);


--
-- Name: transfers fkey2fnrjf4tthac9vmjv4p37t4; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkey2fnrjf4tthac9vmjv4p37t4 FOREIGN KEY (from_base_id) REFERENCES public.bases(id);


--
-- Name: purchases fkftubicnkdkjxj8dxbdfh15exn; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.purchases
    ADD CONSTRAINT fkftubicnkdkjxj8dxbdfh15exn FOREIGN KEY (base_id) REFERENCES public.bases(id);


--
-- Name: expenditures fkhqn09143budjifoqdehka8mwb; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.expenditures
    ADD CONSTRAINT fkhqn09143budjifoqdehka8mwb FOREIGN KEY (equipment_type_id) REFERENCES public.equipment_type(id);


--
-- Name: transfers fkk6wg4rttxkc4mn89j7yv3dly; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.transfers
    ADD CONSTRAINT fkk6wg4rttxkc4mn89j7yv3dly FOREIGN KEY (equipment_type_id) REFERENCES public.equipment_type(id);


--
-- Name: assignments fkm52v5emj0s4ch6qyqhf6oltu0; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkm52v5emj0s4ch6qyqhf6oltu0 FOREIGN KEY (base_id) REFERENCES public.bases(id);


--
-- Name: assignments fkm8cb1vdduype9m8i436fyrlxu; Type: FK CONSTRAINT; Schema: public; Owner: military_admin
--

ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT fkm8cb1vdduype9m8i436fyrlxu FOREIGN KEY (equipment_type_id) REFERENCES public.equipment_type(id);


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON SEQUENCES TO military_admin;


--
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TYPES TO military_admin;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO military_admin;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO military_admin;


--
-- PostgreSQL database dump complete
--

\unrestrict R04ZdVkMHEGeedWPU8zp0oZqw6FbgZyab3MW8J7s8IK6HSTu7LrS7DwZdMHdA4R

